image: adoptopenjdk/openjdk11:alpine-slim

build:
  stage: build
  before_script:
    - mkdir -p .gradle
  script:
    - GRADLE_USER_HOME=.gradle ./gradlew assemble
  artifacts:
    paths:
      - build/
      - cli/build/
      - .gradle/

test:
  stage: test
  services:
    - name: registry.gitlab.com/msrd0/docker-synapse
      alias: synapse
  script:
    - GRADLE_USER_HOME=.gradle ./gradlew test
    - GRADLE_USER_HOME=.gradle ./gradlew jacocoTestReport

pages:
  stage: deploy
  script:
    - GRADLE_USER_HOME=.gradle ./gradlew dokka
    - mv build/javadoc public
  artifacts:
    paths:
      - public
  only:
    - tags
