image: msrd0/gradle

build:
  stage: build
  script:
    - gradle jar
  artifacts:
    paths:
      - build/libs/*.jar
      - cli/build/libs/*.jar
      - cli/build/distributions/*

test:
  stage: test
  script:
    - gradle test


deploy:
  stage: deploy
  script:
    - gradle artifactoryPublish
  only:
    - master
