image: msrd0/gradle

build:
  stage: build
  before_script:
    - mkdir -p .gradle
  script:
    - GRADLE_USER_HOME=.gradle gradle assemble
  artifacts:
    paths:
      - build/
      - cli/build/
      - .gradle/

test:
  stage: test
  services:
    - name: registry.gitlab.com/msrd0/docker-synapse
      alias: synapse
  script:
    - GRADLE_USER_HOME=.gradle gradle test
    - GRADLE_USER_HOME=.gradle gradle jacocoTestReport


deploy:
  stage: deploy
  script:
    - GRADLE_USER_HOME=.gradle gradle artifactoryPublish
  only:
    - master

pages:
  stage: deploy
  script:
    - GRADLE_USER_HOME=.gradle gradle dokka
    - mv build/javadoc public
  artifacts:
    paths:
      - public
  only:
    - master
