image: msrd0/gradle

build:
  stage: build
  script:
    - gradle jar
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - gradle test


deploy:
  stage: deploy
  script:
    - gradle artifactoryPublish
