image: msrd0/gradle

build:
  stage: build
  before_script:
    - mkdir -p .gradle
  script:
    - GRADLE_USER_HOME=.gradle gradle jar
  artifacts:
    paths:
      - build/
      - cli/build/
      - .gradle/

test:
  stage: test
  script:
    - GRADLE_USER_HOME=.gradle gradle test


deploy:
  stage: deploy
  script:
    - GRADLE_USER_HOME=.gradle gradle artifactoryPublish
  only:
    - master
